<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="KLYDUi — A showcase portfolio of hackathon projects by KLYD. Explore innovative builds in AI, blockchain, health tech, and more.">
    <title>KLYDUi — Project Showcase</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@300;400;500;600;700&family=JetBrains+Mono:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles/global.css">
</head>
<body>
    <!-- Gallery wall texture overlay -->
    <div class="wall-texture"></div>

    <!-- Header / Branding -->
    <header class="header" id="header">
        <div class="brand">
            <span class="brand-name">KLYDU<span class="brand-accent">i</span></span>
            <span class="brand-tagline">PROJECT SHOWCASE</span>
        </div>
        <div class="header-right">
            <div class="nav-indicator" id="navIndicator">
                <svg viewBox="0 0 100 100" class="nav-circle">
                    <circle cx="50" cy="50" r="40" class="nav-circle-bg"/>
                    <circle cx="50" cy="50" r="40" class="nav-circle-progress" id="navProgress"/>
                    <circle cx="50" cy="10" r="5" class="nav-dot" id="navDot"/>
                </svg>
                <div class="nav-labels">
                    <span class="nav-label nav-label-top" id="navLabelTop">01</span>
                    <span class="nav-label nav-label-right">05</span>
                    <span class="nav-label nav-label-bottom" id="navLabelBottom">03</span>
                    <span class="nav-label nav-label-left">02</span>
                </div>
            </div>
        </div>
    </header>

    <!-- Gallery Container -->
    <main class="gallery" id="gallery">
        <div class="gallery-track" id="galleryTrack">
            <!-- Project cards will be generated by JS -->
        </div>
    </main>

    <!-- Project Info Overlay -->
    <div class="project-info" id="projectInfo">
        <div class="project-number" id="projectNumber">01</div>
        <div class="project-divider"></div>
        <div class="project-details">
            <h2 class="project-title" id="projectTitle">DataVision</h2>
            <p class="project-description" id="projectDescription">Real-time analytics dashboard</p>
        </div>
        <div class="project-meta">
            <span class="project-tech" id="projectTech">React • D3.js • WebSocket</span>
        </div>
    </div>

    <!-- Navigation Arrows -->
    <nav class="nav-arrows" id="navArrows">
        <button class="nav-arrow nav-arrow-left" id="prevBtn" aria-label="Previous project">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="M15 19l-7-7 7-7"/>
            </svg>
        </button>
        <button class="nav-arrow nav-arrow-right" id="nextBtn" aria-label="Next project">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <path d="M9 5l7 7-7 7"/>
            </svg>
        </button>
    </nav>

    <!-- Bottom Bar -->
    <footer class="footer" id="footer">
        <div class="counter">
            <span class="counter-current" id="counterCurrent">01</span>
            <span class="counter-separator">/</span>
            <span class="counter-total" id="counterTotal">05</span>
        </div>
        <div class="footer-center">
            <div class="scroll-hint">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" class="scroll-icon">
                    <line x1="6" y1="6" x2="18" y2="18"/>
                    <line x1="18" y1="6" x2="6" y2="18"/>
                </svg>
            </div>
        </div>
        <div class="footer-right">
            <span class="copyright">&copy; 2026 KLYDUi. All Rights Reserved.</span>
        </div>
    </footer>

    <!-- Keyboard hint -->
    <div class="keyboard-hint" id="keyboardHint">
        <span>Use</span>
        <kbd>←</kbd>
        <kbd>→</kbd>
        <span>to navigate</span>
    </div>

    <script src="scripts/portfolio.js"></script>
</body>
</html>
